//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitMall.HDQuery.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerAddress
    {
        public int brokerid { get; set; }
        public int AddressId { get; set; }
        public string addressTypeCode { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public Nullable<System.DateTime> terminateDate { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public System.DateTime updatedDate { get; set; }
        public string updatedBy { get; set; }
    
        public virtual Broker Broker { get; set; }
    }
}
