//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitMall.HDQuery.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public Broker()
        {
            this.Licenses = new HashSet<License>();
            this.BrokerAddresses = new HashSet<BrokerAddress>();
        }
    
        public int brokerid { get; set; }
        public Nullable<int> legacybrokeridvalue { get; set; }
        public string shortname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastName { get; set; }
        public Nullable<int> currentPhoneAreaCode { get; set; }
        public string currentPhoneNumber { get; set; }
        public Nullable<int> currentExtensionNumber { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string agencyName { get; set; }
        public Nullable<System.Guid> brokerguid { get; set; }
        public Nullable<System.Guid> employeeguid { get; set; }
        public Nullable<System.Guid> personguid { get; set; }
        public Nullable<System.Guid> brokerPersonGuid { get; set; }
        public string legacyGenID { get; set; }
        public int GeneralagencyID { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public System.DateTime updatedDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<int> BrokerRepresentativeID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> BP_BrokerId { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<bool> IsIncorporated { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<License> Licenses { get; set; }
        public virtual ICollection<BrokerAddress> BrokerAddresses { get; set; }
    }
}
