//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitMall.HDQuery.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public int licenseID { get; set; }
        public string idvalue { get; set; }
        public string name32 { get; set; }
        public string licenseType { get; set; }
        public bool verified { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public Nullable<System.DateTime> terminateDate { get; set; }
        public Nullable<System.Guid> licensetypeguid { get; set; }
        public Nullable<System.Guid> licenseguid { get; set; }
        public string stateCode { get; set; }
        public int brokerid { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public System.DateTime updatedDate { get; set; }
        public string updatedBy { get; set; }
    
        public virtual Broker Broker { get; set; }
    }
}
